import React from 'react'
import { Container } from 'react-bootstrap'
import HexagonButton from '../components/HexagonButton';
import Image from 'next/image'
import greenEarth from '../assets/greenEarth.png' //placeholder
import styles from '../styles/solarPanel.module.css'
import solarPanels from '../assets/solarPanels.jpeg' //placeholder
import roofPanels from '../assets/roofPanels.jpeg' //placeholder
import installPanel from '../assets/installPanel.jpeg' //placeholder


const solarPanel = () => {  return (
    <Container>
        <div>
            <h1 style={{
                marginTop: '2rem'
            }}>Solar Panels</h1>
        </div>
        <div className={styles.solarPanelInfo}>
            <title>Solar Panels</title>
            <h3>What is solar power ?</h3>
            Solar power, one of the most accessible and promising renewable energy sources, takes advantage of Earth&apos;s ultimate energy source—the Sun. Using photovoltaic cells, also called solar cells, and assembling them into panels that can be mounted in a wide variety of places, we can generate power directly using the Sun&apos;s rays for decades without any emission of carbon dioxide.

            <br/><br/><br/><br/>

            <figure>
                <Image 
                    style={{
                    width: '100%',
                    height: '100%',
                    pointerEvents: 'none',
                    marginTop: ' 2rem'
                }}
                src={solarPanels}
                alt='Solar panels absorbing the sun.'
                />
                <figcaption style={{
                fontStyle: 'italic'
                }}>You may not have this quantity of panels, but the effects will still be worth it in the long run.</figcaption>
            </figure>

            <br/><br/><br/><br/>

            <title>Solar Advantages</title>
            <h3>What are the advantages to solar power?</h3>
            Unlike many other sources of energy, including forms of renewable energy, solar cells have no moving parts. This allows them to work quietly, efficiently, and with much less technical maintenance. Solar cells can work at both large and small scales, able to form essential parts of power generating facilities and power personal devices.
            <br/><br/>
            Solar cells also work wherever the sun shines: everywhere! Even in places that don&apos;t get as much direct sunlight, solar cells can still be a cost-effective and efficient way to generate power without as much infrastructure. Those in remote locations can take advantage of the power of the Sun and gain access to electricity where they likely couldn&apos;t before.
            <br/><br/>
            Of course, solar power is a renewable resource, which means that producing energy via solar cells emits no carbon dioxide. Energy generated by solar power is clean and pure, and usage of solar power greatly decreases our reliance on greenhouse-gas emitting energy resources and therefore our impact on the environment, including with pollution.
            <br/><br/>
            
            <title>Solar for Home</title>
            <h3>How can homeowners take advantage of solar power?</h3>
            In recent years, it&apos;s become far more feasible for homeowners to host solar cells on their roofs and generate green electricity for themselves. By pairing solar setups with a battery or connecting them up to the grid, homeowners can reduce their energy bills—or even eliminate them entirely. This allows them to offset the cost of installation and begin saving money on electricity within the span of a few years. Once solar setups are installed, they can increase the value of a home as well due to these advantages.

            <br/><br/><br/><br/>

            <Image 
                    style={{
                    width: '100%',
                    height: '100%',
                    pointerEvents: 'none',
                    marginTop: ' 2rem'
                }}
                src={roofPanels}
                alt='Solar panels on roof.'
            />

            <br/><br/><br/><br/>            

            <title>Monetary Advantages</title>
            <h3>How can solar power help homeowners monetarily?</h3>
            In addition to the advantages described above, homeowners are eligible for tax credits by installing solar setups in their homes. These tax credits directly reduce the amount of income tax that they owe by a percentage of the cost of installation of the solar system. The Residential Clean Energy Credit, a federal level tax credit, releases homeowners from paying tax equivalent to 30% of the cost to install solar until 2032. After 2032, the percentage decreases to 26% and 22%, so homeowners should begin planning to improve their homes and lives with solar today! 
            <br/><br/><br/><br/>

            <Image 
                    style={{
                    width: '100%',
                    height: '100%',
                    pointerEvents: 'none',
                    marginTop: ' 2rem'
                }}
                src={installPanel}
                alt='Workers installing panels.'
            />

            <HexagonButton/>
        </div>
        
    </Container>
    )
}

export default solarPanel